[server]
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 200
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = true
fastReruns = true
enforceSerializableSessionState = false

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[logger]
level = "error"
